version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.x
    commands:
      echo "Installing dependencies..."

  pre_build:
    commands:
      echo "Preparing for deployment..."

  build:
    commands:
      echo "Building files..."

  post_build:
    commands:
      echo "Deploying static files to S3..."
      aws s3 sync Static/ s3://aws-sksu-poc-staticpage-codepipeline-test-01/ --delete
