version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.x
    commands:
      # Install dependencies if needed for Lambda
      echo "Installing dependencies..."
      pip install -r Dynamic/requirements.txt || true

  pre_build:
    commands:
      echo "Preparing for deployment..."

  build:
    commands:
      echo "Building files..."

  post_build:
    commands:
      # Deploy static files to S3
      echo "Deploying static files to S3..."
      aws s3 sync Static/ s3://aws-sksu-poc-staticpage-codepipeline-test-01/ --delete

      # Deploy dynamic files to Lambda
      echo "Deploying dynamic files to Lambda..."
      zip -r dynamic.zip Dynamic/
      aws lambda update-function-code --function-name aws-sksu-poc-staticpage-lambda-codepipeline-test-01 --zip-file fileb://dynamic.zip

artifacts:
  files:
    - '**/*'
